wip
jcpaik/conway-soifer-triangle pull request #8
Opened 2023-07-22 09:32 UTC by seewoo5

2023-07-22 10:10 UTC, seewoo5 commented
확인하고 필요없는 주석들 지워도 될듯?

2023-07-24 02:50 UTC, jcpaik requested changes

2023-07-24 02:50 UTC, jcpaik commented on main.tex
> +We will use different $r \in \mathcal{T}$ depending on the parity of $n$, which can be hinted by the constructions in Section \ref{sec:description} (Figure \ref{fig:triangle3}).
parity얘기만 빼주셈

2023-07-24 05:51 UTC, seewoo5 commented on main.tex
> +We will use different $r \in \mathcal{T}$ depending on the parity of $n$, which can be hinted by the constructions in Section \ref{sec:description} (Figure \ref{fig:triangle3}).
fixed!

2023-07-24 07:35 UTC, jcpaik approved these changes

2023-07-24 07:35 UTC, jcpaik commented
이거 지금 이대로도 좋은데, 위에 커멘트 단것처럼 n^2+2랑 n^2+3이랑 한방에 설명 가능한거 같음

2023-07-24 07:36 UTC, jcpaik commented
지금부턴 내가 요거 수정해볼게 (너가 위에 내가 스케치한것처럼 증명 합칠 수 있을거 같으면 해도됨)

2023-07-24 22:59 UTC, seewoo5 commented
> 왜 n^2+2는 1/(n+1)인데 n^2+3은 1/n인지 의문이었어서 정리해봄.
> 
> n+eps짜리 삼각형에서 n짜리 삼각형을 빼고, 마주보는 삼각형 두개를 뺀것 (g = f_T - f_{T_0} - Delta_0 - Nabla_0)의 projection + mod Z한 함수는 상수함수인데 한쪽 끝이 살짝 올라가있음
> 
> eps=1/(n+1)은 g의 올라간 끝이 0 이하가 되는 최대값이고 eps=1/n은 g의 상수(평평한 부분)값이 0 이하가 되는 최대값임
> 
> n^2+2일때는 g보다 큰 h가 적분값이 딱 0이어야 함. 그래서 올라간 끝이 0보다 크면 안됨 n^2+2일때는 h가 적분값이 1/2여야 함. 그래서 평평한 부분이 0보다 크면 안됨

이걸로 n^2 + 4가 (지금 접근으로는) 쉽지 않을것이라는것도 설명이 될 것 같군요

2023-08-01 16:14 UTC, seewoo5 commented
그림 틀린부분 있어서 수정해서 push했음

2023-08-04 14:09 UTC, jcpaik commented
@seewoo5 확인좀 (리뷰신청할려 했는데 너가 author여서 못함)

2023-08-04 18:27 UTC, seewoo5 commented on main.tex
> +Without loss of generality, assume that the bottom side of $T$ is the $x$-axis so that $y_T = 0$.
$y_T$ -> $z_T$?

2023-08-04 18:27 UTC, seewoo5 commented on main.tex
> +      \tkzInit[xmin = -0.5, xmax = 1, ymin = -0.5, ymax = 0.5]
그림에서 y축이랑 숫자1이 겹치는데 `ymax` 키우면 좀 더 보기좋을듯

2023-08-04 18:27 UTC, seewoo5 commented
코멘트만 반영되면 바로 머지 ㄱㄱ

2023-08-05 06:12 UTC, jcpaik commented on main.tex
> +      \tkzInit[xmin = -0.5, xmax = 1, ymin = -0.5, ymax = 0.5]
숫자 1 어케 없앨지 모르겠음 ㅜㅜ ymax값 줄였는데도 계속 뜬다

2023-08-05 06:33 UTC, jcpaik commented on main.tex
> +      \tkzInit[xmin = -0.5, xmax = 1, ymin = -0.5, ymax = 0.5]
아 ymax를 늘이라는거군 늘렸음

2023-08-05 06:33 UTC, jcpaik commented on main.tex
> +Without loss of generality, assume that the bottom side of $T$ is the $x$-axis so that $y_T = 0$.
굿

2023-08-05 06:36 UTC, merged